name: macos
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cruby-test-system-libraries:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set ENV
        run: |
          echo "MAKEFLAGS=-j$((1 + $(sysctl -n hw.activecpu)))" >> $GITHUB_ENV
          echo "NOKOGIRI_USE_SYSTEM_LIBRARIES=t" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '2.7'
      - run: bundle exec rake compile
      - run: bundle exec rake test

  cruby-test-vendored-libraries:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ports/archives
          key: tarballs-${{ hashFiles('**/dependencies.yml') }}
          restore-keys: |
            tarballs-

      - name: Set ENV
        run: |
          echo "MAKEFLAGS=-j$((1 + $(sysctl -n hw.activecpu)))" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '2.7'
      - run: bundle exec rake compile
      - run: bundle exec rake test
